package at.struct.was9bugs.bug18.mywebservice;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2018-02-21T13:28:22.174+01:00
 * Generated source version: 2.6.16
 * 
 */
@WebServiceClient(name = "myWebservice", 
                  wsdlLocation = "classpath:MyWebservice.wsdl",
                  targetNamespace = "http://was9bugs.struct.at/Webservice/MyWebservice/") 
public class MyWebservice_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://was9bugs.struct.at/Webservice/MyWebservice/", "myWebservice");
    public final static QName MyWebservicePort = new QName("http://was9bugs.struct.at/Webservice/MyWebservice/", "MyWebservicePort");
    static {
        URL url = MyWebservice_Service.class.getClassLoader().getResource("MyWebservice.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(MyWebservice_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "classpath:MyWebservice.wsdl");
        }       
        WSDL_LOCATION = url;   
    }

    public MyWebservice_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public MyWebservice_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MyWebservice_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyWebservice_Service(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyWebservice_Service(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public MyWebservice_Service(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns MyWebservice
     */
    @WebEndpoint(name = "MyWebservicePort")
    public MyWebservice getMyWebservicePort() {
        return super.getPort(MyWebservicePort, MyWebservice.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MyWebservice
     */
    @WebEndpoint(name = "MyWebservicePort")
    public MyWebservice getMyWebservicePort(WebServiceFeature... features) {
        return super.getPort(MyWebservicePort, MyWebservice.class, features);
    }

}
