package at.struct.was9bugs.bug18.mywebservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.16
 * 2018-02-21T13:28:22.139+01:00
 * Generated source version: 2.6.16
 * 
 */
@WebService(targetNamespace = "http://was9bugs.struct.at/Webservice/MyWebservice/", name = "MyWebservice")
@XmlSeeAlso({ObjectFactory.class})
public interface MyWebservice {

    @WebMethod(action = "http://was9bugs.struct.at/Webservice/MyWebservice/webserviceMethod/")
    @RequestWrapper(localName = "webserviceMethod", targetNamespace = "http://was9bugs.struct.at/Webservice/MyWebservice/", className = "at.struct.was9bugs.bug18.mywebservice.WebserviceMethod")
    @ResponseWrapper(localName = "webserviceMethodResponse", targetNamespace = "http://was9bugs.struct.at/Webservice/MyWebservice/", className = "at.struct.was9bugs.bug18.mywebservice.WebserviceMethodResponse")
    @WebResult(name = "response", targetNamespace = "")
    public at.struct.was9bugs.bug18.mywebservice.MyWebserviceResponse webserviceMethod(
        @WebParam(name = "request", targetNamespace = "")
        at.struct.was9bugs.bug18.mywebservice.MyWebserviceRequest request
    );
}
